/**
 * Autonomous Development Workflows
 * 
 * Defines the workflows that the Mossbot AI Agent executes for autonomous development
 */

import { AgentContext, AgentTask, WorkflowStep, TaskStatus } from "./agentSystem";
import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

/**
 * Execute shell command in project directory
 */
function executeCommand(command: string, cwd: string): string {
  try {
    const result = execSync(command, { cwd, encoding: "utf-8" });
    return result;
  } catch (error) {
    throw new Error(`Command failed: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Feature Development Workflow Steps
 */
export const featureDevelopmentWorkflow: WorkflowStep[] = [
  {
    name: "analyze_requirements",
    description: "Analyze task requirements and dependencies",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Analyzing requirements for: ${task.title}`);

      // Parse acceptance criteria and dependencies
      const criteria = task.acceptanceCriteria;
      const deps = task.dependencies;

      console.log(`  - Acceptance Criteria: ${criteria.length} items`);
      console.log(`  - Dependencies: ${deps.length} items`);

      return true;
    },
  },
  {
    name: "design_solution",
    description: "Design solution architecture",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Designing solution for: ${task.title}`);

      // Create design document
      const designDoc = `# Design: ${task.title}\n\n## Overview\n${task.description}\n\n## Acceptance Criteria\n${task.acceptanceCriteria.map(c => `- ${c}`).join("\n")}\n`;

      const designPath = path.join(context.projectPath, ".agent", "designs", `${task.id}.md`);
      const designDir = path.dirname(designPath);

      if (!fs.existsSync(designDir)) {
        fs.mkdirSync(designDir, { recursive: true });
      }

      fs.writeFileSync(designPath, designDoc);
      console.log(`  - Design document created: ${designPath}`);

      return true;
    },
  },
  {
    name: "create_feature_branch",
    description: "Create feature branch in git",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Creating feature branch`);

      try {
        const branchName = `feature/${task.id.replace(/[^a-z0-9]/g, "-").toLowerCase()}`;

        // Ensure we're on main and up to date
        executeCommand("git checkout main", context.projectPath);
        executeCommand("git pull origin main", context.projectPath);

        // Create and checkout feature branch
        executeCommand(`git checkout -b ${branchName}`, context.projectPath);

        console.log(`  - Branch created: ${branchName}`);
        return true;
      } catch (error) {
        console.error(`  - Error creating branch: ${error}`);
        return false;
      }
    },
  },
  {
    name: "implement_code",
    description: "Implement feature code",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Implementing code for: ${task.title}`);

      // In a real implementation, this would use LLM to generate code
      // For now, we'll create a placeholder implementation
      const implPath = path.join(context.projectPath, ".agent", "implementations", `${task.id}.ts`);
      const implDir = path.dirname(implPath);

      if (!fs.existsSync(implDir)) {
        fs.mkdirSync(implDir, { recursive: true });
      }

      const implementation = `// Implementation: ${task.title}\n// Generated by Mossbot AI Agent\n\n${task.description}\n`;
      fs.writeFileSync(implPath, implementation);

      console.log(`  - Implementation file created: ${implPath}`);
      return true;
    },
  },
  {
    name: "write_tests",
    description: "Write comprehensive tests",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Writing tests for: ${task.title}`);

      // Create test file
      const testPath = path.join(
        context.projectPath,
        ".agent",
        "tests",
        `${task.id}.test.ts`
      );
      const testDir = path.dirname(testPath);

      if (!fs.existsSync(testDir)) {
        fs.mkdirSync(testDir, { recursive: true });
      }

      const testContent = `import { describe, it, expect } from "vitest";\n\ndescribe("${task.title}", () => {\n  ${task.acceptanceCriteria.map(c => `it("should ${c}", () => {\n    expect(true).toBe(true);\n  });`).join("\n  ")}\n});\n`;

      fs.writeFileSync(testPath, testContent);
      console.log(`  - Test file created: ${testPath}`);

      // Run tests
      try {
        executeCommand("pnpm test", context.projectPath);
        console.log(`  - Tests passed`);
        return true;
      } catch (error) {
        console.error(`  - Tests failed: ${error}`);
        return false;
      }
    },
  },
  {
    name: "validate_quality",
    description: "Validate code quality and standards",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Validating code quality`);

      try {
        // Run TypeScript check
        executeCommand("pnpm tsc --noEmit", context.projectPath);
        console.log(`  - TypeScript check passed`);

        // Run linter
        executeCommand("pnpm lint", context.projectPath);
        console.log(`  - Linter check passed`);

        return true;
      } catch (error) {
        console.error(`  - Quality check failed: ${error}`);
        return false;
      }
    },
  },
  {
    name: "commit_and_push",
    description: "Commit changes and push to repository",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Committing and pushing changes`);

      try {
        // Stage changes
        executeCommand("git add .", context.projectPath);

        // Create commit
        const commitMessage = `feat: ${task.title}\n\n${task.description}\n\nAcceptance Criteria:\n${task.acceptanceCriteria.map(c => `- ${c}`).join("\n")}`;
        executeCommand(`git commit -m "${commitMessage}"`, context.projectPath);

        // Push to origin
        const branchName = `feature/${task.id.replace(/[^a-z0-9]/g, "-").toLowerCase()}`;
        executeCommand(`git push origin ${branchName}`, context.projectPath);

        console.log(`  - Changes committed and pushed`);
        return true;
      } catch (error) {
        console.error(`  - Commit failed: ${error}`);
        return false;
      }
    },
  },
];

/**
 * Bug Fix Workflow Steps
 */
export const bugFixWorkflow: WorkflowStep[] = [
  {
    name: "reproduce_bug",
    description: "Reproduce the bug",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Reproducing bug: ${task.title}`);

      // Create reproduction steps document
      const reproPath = path.join(context.projectPath, ".agent", "bugs", `${task.id}-repro.md`);
      const reproDir = path.dirname(reproPath);

      if (!fs.existsSync(reproDir)) {
        fs.mkdirSync(reproDir, { recursive: true });
      }

      const reproDoc = `# Bug Reproduction: ${task.title}\n\n## Description\n${task.description}\n\n## Steps to Reproduce\n${task.acceptanceCriteria.map(c => `1. ${c}`).join("\n")}\n`;

      fs.writeFileSync(reproPath, reproDoc);
      console.log(`  - Reproduction document created: ${reproPath}`);

      return true;
    },
  },
  {
    name: "identify_root_cause",
    description: "Identify root cause",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Identifying root cause for: ${task.title}`);

      // Create root cause analysis document
      const rcaPath = path.join(context.projectPath, ".agent", "bugs", `${task.id}-rca.md`);
      const rcaDoc = `# Root Cause Analysis: ${task.title}\n\n## Issue\n${task.description}\n\n## Analysis\nInvestigating the codebase for the root cause...\n`;

      fs.writeFileSync(rcaPath, rcaDoc);
      console.log(`  - RCA document created: ${rcaPath}`);

      return true;
    },
  },
  {
    name: "implement_fix",
    description: "Implement fix",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Implementing fix for: ${task.title}`);

      // Create fix file
      const fixPath = path.join(context.projectPath, ".agent", "fixes", `${task.id}.ts`);
      const fixDir = path.dirname(fixPath);

      if (!fs.existsSync(fixDir)) {
        fs.mkdirSync(fixDir, { recursive: true });
      }

      const fixContent = `// Fix for: ${task.title}\n// Issue: ${task.description}\n`;
      fs.writeFileSync(fixPath, fixContent);

      console.log(`  - Fix implemented: ${fixPath}`);
      return true;
    },
  },
  {
    name: "write_regression_test",
    description: "Write regression test",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Writing regression test`);

      // Create regression test
      const testPath = path.join(
        context.projectPath,
        ".agent",
        "tests",
        `${task.id}-regression.test.ts`
      );
      const testDir = path.dirname(testPath);

      if (!fs.existsSync(testDir)) {
        fs.mkdirSync(testDir, { recursive: true });
      }

      const testContent = `import { describe, it, expect } from "vitest";\n\ndescribe("Regression: ${task.title}", () => {\n  it("should not reproduce the bug", () => {\n    expect(true).toBe(true);\n  });\n});\n`;

      fs.writeFileSync(testPath, testContent);
      console.log(`  - Regression test created: ${testPath}`);

      return true;
    },
  },
  {
    name: "commit_and_push",
    description: "Commit changes and push to repository",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Committing bug fix`);

      try {
        // Stage changes
        executeCommand("git add .", context.projectPath);

        // Create commit
        const commitMessage = `fix: ${task.title}\n\n${task.description}`;
        executeCommand(`git commit -m "${commitMessage}"`, context.projectPath);

        // Push to origin
        const branchName = `fix/${task.id.replace(/[^a-z0-9]/g, "-").toLowerCase()}`;
        executeCommand(`git push origin ${branchName}`, context.projectPath);

        console.log(`  - Bug fix committed and pushed`);
        return true;
      } catch (error) {
        console.error(`  - Commit failed: ${error}`);
        return false;
      }
    },
  },
];

/**
 * Documentation Workflow Steps
 */
export const documentationWorkflow: WorkflowStep[] = [
  {
    name: "analyze_documentation_needs",
    description: "Analyze documentation requirements",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Analyzing documentation needs`);
      return true;
    },
  },
  {
    name: "generate_documentation",
    description: "Generate documentation content",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Generating documentation: ${task.title}`);

      // Create documentation file
      const docPath = path.join(context.projectPath, "docs", `${task.id}.md`);
      const docDir = path.dirname(docPath);

      if (!fs.existsSync(docDir)) {
        fs.mkdirSync(docDir, { recursive: true });
      }

      const docContent = `# ${task.title}\n\n${task.description}\n\n## Contents\n${task.acceptanceCriteria.map(c => `- ${c}`).join("\n")}\n`;

      fs.writeFileSync(docPath, docContent);
      console.log(`  - Documentation created: ${docPath}`);

      return true;
    },
  },
  {
    name: "commit_and_push",
    description: "Commit documentation",
    execute: async (context: AgentContext, task: AgentTask) => {
      console.log(`[${context.agentId}] Committing documentation`);

      try {
        executeCommand("git add docs/", context.projectPath);
        const commitMessage = `docs: ${task.title}`;
        executeCommand(`git commit -m "${commitMessage}"`, context.projectPath);
        executeCommand("git push origin main", context.projectPath);

        console.log(`  - Documentation committed`);
        return true;
      } catch (error) {
        console.error(`  - Commit failed: ${error}`);
        return false;
      }
    },
  },
];

/**
 * Get workflow for task category
 */
export function getWorkflowForCategory(category: string): WorkflowStep[] {
  switch (category) {
    case "bug":
      return bugFixWorkflow;
    case "documentation":
      return documentationWorkflow;
    case "feature":
    default:
      return featureDevelopmentWorkflow;
  }
}
